@HostAddress = http://localhost:5192

GET {{HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{HostAddress}}/api/orders
Content-Type: application/json

{
    "items": [
        {
            "productId": "24370648-e13a-46d9-994f-123456789012",
            "quantity": 1,
          
        }
    ]
}